# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72618782e7dcd2173ce1e288a9d07681950f7e22d978d9691cd29955f8d1c7b36b9fbb5fbfe76d733f4695e4314d76f5a66ca3ee5179f4a487c021ff7da0fb09

test:
  secret_key_base: d9f2567a59723ccdb708f6184f13570dceec34b1b78bb371b70f83942677e0f75fcccee8990133e05eb9188d43dd418d6d929cfda1cab8eae5a14aa1dbb85baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
